# Funding links for Zentinel
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [zentinelproxy]
open_collective: zentinel-proxy
ko_fi: raskell
custom: ["https://zentinelproxy.io/support"]
