//! Writes translated Gateway API config as a KDL file for the proxy to read.
//!
//! The gateway controller translates K8s resources into a `Config`, then
//! this module serializes it to a KDL file on a shared volume. The Zentinel
//! proxy runs alongside with `auto-reload: true` and picks up changes
//! automatically via file watching.
//!
//! This is the bridge between the gateway controller (control plane) and
//! the proxy (data plane) in the two-container deployment model.

use std::path::{Path, PathBuf};
use tracing::info;

use zentinel_config::{Config, Filter, HeaderModifications, PathModifier};

/// Writes a `Config` to a KDL file that the proxy can read.
pub struct ConfigWriter {
    output_path: PathBuf,
}

impl ConfigWriter {
    pub fn new(output_path: PathBuf) -> Self {
        Self { output_path }
    }

    /// Write the config to disk as KDL.
    ///
    /// Uses an atomic write pattern: write to a temp file, then rename.
    /// This prevents the proxy from reading a partially-written file.
    pub fn write(&self, config: &Config) -> Result<(), std::io::Error> {
        let kdl = self.render_kdl(config);

        // Write atomically via temp file + rename, then re-touch the output
        // file to ensure inotify fires IN_MODIFY (rename only fires
        // IN_MOVED_TO on the directory, which some watchers miss).
        let tmp_path = self.output_path.with_extension("kdl.tmp");
        std::fs::write(&tmp_path, &kdl)?;
        std::fs::rename(&tmp_path, &self.output_path)?;

        // Touch the file to trigger IN_CLOSE_WRITE / IN_MODIFY
        let file = std::fs::OpenOptions::new()
            .append(true)
            .open(&self.output_path)?;
        drop(file);

        info!(
            path = %self.output_path.display(),
            routes = config.routes.len(),
            upstreams = config.upstreams.len(),
            listeners = config.listeners.len(),
            bytes = kdl.len(),
            "Config written to disk"
        );

        Ok(())
    }

    /// Get the output path.
    pub fn output_path(&self) -> &Path {
        &self.output_path
    }

    /// Render a Config as KDL text.
    ///
    /// This produces a minimal but complete KDL config that the proxy can
    /// parse. We generate it programmatically rather than using serde because
    /// the KDL format has specific structure expectations.
    fn render_kdl(&self, config: &Config) -> String {
        let mut out = String::with_capacity(4096);

        out.push_str("// Auto-generated by zentinel-gateway controller\n");
        out.push_str("// Do not edit manually, changes will be overwritten\n\n");

        out.push_str(&format!("schema-version \"{}\"\n\n", config.schema_version));

        // System block
        out.push_str("system {\n");
        out.push_str(&format!(
            "    worker-threads {}\n",
            config.server.worker_threads
        ));
        if config.server.auto_reload {
            out.push_str("    auto-reload #true\n");
        }
        out.push_str("}\n\n");

        // Listeners
        out.push_str("listeners {\n");
        for listener in &config.listeners {
            out.push_str(&format!("    listener \"{}\" {{\n", listener.id));
            out.push_str(&format!("        address \"{}\"\n", listener.address));
            let proto = match listener.protocol {
                zentinel_config::ListenerProtocol::Http => "http",
                zentinel_config::ListenerProtocol::Https => "https",
                _ => "http",
            };
            out.push_str(&format!("        protocol \"{proto}\"\n"));

            if let Some(ref tls) = listener.tls {
                out.push_str("        tls {\n");
                if let Some(ref cert) = tls.cert_file {
                    out.push_str(&format!("            cert-file \"{}\"\n", cert.display()));
                }
                if let Some(ref key) = tls.key_file {
                    out.push_str(&format!("            key-file \"{}\"\n", key.display()));
                }
                out.push_str("        }\n");
            }

            out.push_str("    }\n");
        }
        out.push_str("}\n\n");

        // Upstreams
        if !config.upstreams.is_empty() {
            out.push_str("upstreams {\n");
            for (id, upstream) in &config.upstreams {
                out.push_str(&format!("    upstream \"{}\" {{\n", id));
                for target in &upstream.targets {
                    out.push_str(&format!("        target \"{}\"", target.address));
                    if target.weight != 1 {
                        out.push_str(&format!(" weight={}", target.weight));
                    }
                    out.push('\n');
                }

                if let Some(ref hc) = upstream.health_check {
                    out.push_str("        health-check {\n");
                    match &hc.check_type {
                        zentinel_common::types::HealthCheckType::Http {
                            path,
                            expected_status,
                            host,
                        } => {
                            out.push_str("            type \"http\"\n");
                            out.push_str(&format!("            path \"{path}\"\n"));
                            out.push_str(&format!(
                                "            expected-status {expected_status}\n"
                            ));
                            if let Some(ref h) = host {
                                out.push_str(&format!("            host \"{h}\"\n"));
                            }
                        }
                        zentinel_common::types::HealthCheckType::Tcp => {
                            out.push_str("            type \"tcp\"\n");
                        }
                        zentinel_common::types::HealthCheckType::Grpc { service } => {
                            out.push_str("            type \"grpc\"\n");
                            if !service.is_empty() {
                                out.push_str(&format!("            service \"{service}\"\n"));
                            }
                        }
                        _ => {
                            out.push_str("            type \"tcp\"\n");
                        }
                    }
                    out.push_str(&format!("            interval-secs {}\n", hc.interval_secs));
                    out.push_str(&format!("            timeout-secs {}\n", hc.timeout_secs));
                    out.push_str("        }\n");
                }

                out.push_str("    }\n");
            }
            out.push_str("}\n\n");
        }

        // Filters (redirect, rewrite, etc.)
        if !config.filters.is_empty() {
            out.push_str("filters {\n");
            for (id, fc) in &config.filters {
                match &fc.filter {
                    Filter::Redirect(r) => {
                        out.push_str(&format!("    filter \"{id}\" {{\n"));
                        out.push_str("        type \"redirect\"\n");
                        out.push_str(&format!("        status-code {}\n", r.status_code));
                        if let Some(ref h) = r.hostname {
                            out.push_str(&format!("        hostname \"{h}\"\n"));
                        }
                        if let Some(ref s) = r.scheme {
                            out.push_str(&format!("        scheme \"{s}\"\n"));
                        }
                        if let Some(port) = r.port {
                            out.push_str(&format!("        port {port}\n"));
                        }
                        if let Some(ref path) = r.path {
                            render_path_modifier(&mut out, path, 8);
                        }
                        out.push_str("    }\n");
                    }
                    Filter::UrlRewrite(r) => {
                        out.push_str(&format!("    filter \"{id}\" {{\n"));
                        out.push_str("        type \"url-rewrite\"\n");
                        if let Some(ref h) = r.hostname {
                            out.push_str(&format!("        hostname \"{h}\"\n"));
                        }
                        if let Some(ref path) = r.path {
                            render_path_modifier(&mut out, path, 8);
                        }
                        out.push_str("    }\n");
                    }
                    _ => {}
                }
            }
            out.push_str("}\n\n");
        }

        // Routes
        if !config.routes.is_empty() {
            out.push_str("routes {\n");
            for route in &config.routes {
                out.push_str(&format!("    route \"{}\" {{\n", route.id));

                // Priority (if not default)
                if route.priority != zentinel_common::types::Priority::Normal {
                    let prio_str = match route.priority {
                        zentinel_common::types::Priority::Critical => "high",
                        zentinel_common::types::Priority::High => "high",
                        zentinel_common::types::Priority::Normal => "normal",
                        zentinel_common::types::Priority::Low => "low",
                    };
                    out.push_str(&format!("        priority \"{prio_str}\"\n"));
                }

                // Match conditions
                out.push_str("        matches {\n");
                for m in &route.matches {
                    match m {
                        zentinel_config::MatchCondition::PathPrefix(p) => {
                            out.push_str(&format!("            path-prefix \"{p}\"\n"));
                        }
                        zentinel_config::MatchCondition::Path(p) => {
                            out.push_str(&format!("            path \"{p}\"\n"));
                        }
                        zentinel_config::MatchCondition::PathRegex(p) => {
                            out.push_str(&format!("            path-regex \"{p}\"\n"));
                        }
                        zentinel_config::MatchCondition::Host(h) => {
                            out.push_str(&format!("            host \"{h}\"\n"));
                        }
                        zentinel_config::MatchCondition::Header { name, value } => {
                            if let Some(v) = value {
                                out.push_str(&format!("            header \"{name}\" \"{v}\"\n"));
                            } else {
                                out.push_str(&format!("            header \"{name}\"\n"));
                            }
                        }
                        zentinel_config::MatchCondition::Method(methods) => {
                            for method in methods {
                                out.push_str(&format!("            method \"{method}\"\n"));
                            }
                        }
                        zentinel_config::MatchCondition::QueryParam { name, value } => {
                            if let Some(v) = value {
                                out.push_str(&format!(
                                    "            query-param \"{name}\" \"{v}\"\n"
                                ));
                            }
                        }
                    }
                }
                out.push_str("        }\n");

                if let Some(ref upstream) = route.upstream {
                    out.push_str(&format!("        upstream \"{upstream}\"\n"));
                }

                // Route-level filters (referenced by ID)
                if !route.filters.is_empty() {
                    out.push_str("        filters");
                    for filter_id in &route.filters {
                        out.push_str(&format!(" \"{filter_id}\""));
                    }
                    out.push('\n');
                }

                // Policies block (header modifications)
                let req_h = &route.policies.request_headers;
                let res_h = &route.policies.response_headers;
                let has_req = !req_h.set.is_empty()
                    || !req_h.add.is_empty()
                    || !req_h.remove.is_empty();
                let has_res = !res_h.set.is_empty()
                    || !res_h.add.is_empty()
                    || !res_h.remove.is_empty();

                if has_req || has_res {
                    out.push_str("        policies {\n");

                    if has_req {
                        out.push_str("            request-headers {\n");
                        render_header_mods_block(&mut out, req_h, 16);
                        out.push_str("            }\n");
                    }

                    if has_res {
                        out.push_str("            response-headers {\n");
                        render_header_mods_block(&mut out, res_h, 16);
                        out.push_str("            }\n");
                    }

                    out.push_str("        }\n");
                }

                out.push_str("    }\n");
            }
            out.push_str("}\n");
        }

        out
    }
}

/// Render header modifications in the nested structure the parser expects:
/// ```kdl
/// set {
///     Header-Name "value"
/// }
/// add {
///     Header-Name "value"
/// }
/// remove "Header-Name" "Other-Header"
/// ```
fn render_header_mods_block(out: &mut String, mods: &HeaderModifications, indent: usize) {
    let pad: String = " ".repeat(indent);
    if !mods.set.is_empty() {
        out.push_str(&format!("{pad}set {{\n"));
        for (k, v) in &mods.set {
            out.push_str(&format!("{pad}    {k} \"{v}\"\n"));
        }
        out.push_str(&format!("{pad}}}\n"));
    }
    if !mods.add.is_empty() {
        out.push_str(&format!("{pad}add {{\n"));
        for (k, v) in &mods.add {
            out.push_str(&format!("{pad}    {k} \"{v}\"\n"));
        }
        out.push_str(&format!("{pad}}}\n"));
    }
    if !mods.remove.is_empty() {
        out.push_str(&format!("{pad}remove"));
        for k in &mods.remove {
            out.push_str(&format!(" \"{k}\""));
        }
        out.push('\n');
    }
}

/// Render a `PathModifier` as KDL at the given indentation level.
fn render_path_modifier(out: &mut String, path: &PathModifier, indent: usize) {
    let pad: String = " ".repeat(indent);
    match path {
        PathModifier::ReplaceFullPath { value } => {
            out.push_str(&format!("{pad}replace-full-path \"{value}\"\n"));
        }
        PathModifier::ReplacePrefixMatch { value } => {
            out.push_str(&format!("{pad}replace-prefix-match \"{value}\"\n"));
        }
    }
}

/// Write a minimal bootstrap config for the proxy to start with before
/// the controller has reconciled any Gateway API resources.
pub fn write_bootstrap_config(path: &Path) -> Result<(), std::io::Error> {
    let kdl = r#"// Bootstrap config for Zentinel Gateway API controller
// Will be overwritten once the controller reconciles Gateway resources

schema-version "1.0"

system {
    worker-threads 0
    auto-reload #true
}

listeners {
    listener "http" {
        address "0.0.0.0:8080"
        protocol "http"
    }
    listener "https" {
        address "0.0.0.0:8443"
        protocol "http"
    }
}
"#;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, kdl)?;
    info!(path = %path.display(), "Bootstrap config written");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use zentinel_common::types::{LoadBalancingAlgorithm, Priority};
    use zentinel_config::{
        ConnectionPoolConfig, FilterConfig, HeaderModifications, HttpVersionConfig,
        ListenerConfig, ListenerProtocol, MatchCondition, RedirectFilter, RoutePolicies,
        RouteConfig, ServerConfig, ServiceType, UpstreamConfig, UpstreamTarget,
        UpstreamTimeouts,
    };

    /// Build a Config with routes, upstreams, filters, and header policies,
    /// render it to KDL, and verify the proxy parser can read it back.
    #[test]
    fn round_trip_rendered_kdl_parses_successfully() {
        let mut filters = HashMap::new();
        filters.insert(
            "redir-0".to_string(),
            FilterConfig::new(
                "redir-0",
                Filter::Redirect(RedirectFilter {
                    hostname: Some("example.com".to_string()),
                    status_code: 301,
                    scheme: Some("https".to_string()),
                    port: None,
                    path: Some(PathModifier::ReplaceFullPath {
                        value: "/new".to_string(),
                    }),
                }),
            ),
        );

        let mut upstreams = HashMap::new();
        upstreams.insert(
            "backend".to_string(),
            UpstreamConfig {
                id: "backend".to_string(),
                targets: vec![
                    UpstreamTarget {
                        address: "svc.default.svc.cluster.local:80".to_string(),
                        weight: 3,
                        max_requests: None,
                        metadata: HashMap::new(),
                    },
                    UpstreamTarget {
                        address: "svc2.default.svc.cluster.local:80".to_string(),
                        weight: 1,
                        max_requests: None,
                        metadata: HashMap::new(),
                    },
                ],
                load_balancing: LoadBalancingAlgorithm::RoundRobin,
                sticky_session: None,
                health_check: None,
                connection_pool: ConnectionPoolConfig::default(),
                timeouts: UpstreamTimeouts::default(),
                tls: None,
                http_version: HttpVersionConfig::default(),
            },
        );

        let config = Config {
            schema_version: "1.0".to_string(),
            server: ServerConfig {
                worker_threads: 0,
                max_connections: 10000,
                graceful_shutdown_timeout_secs: 30,
                daemon: false,
                pid_file: None,
                user: None,
                group: None,
                working_directory: None,
                trace_id_format: Default::default(),
                auto_reload: true,
            },
            listeners: vec![ListenerConfig {
                id: "http".to_string(),
                address: "0.0.0.0:8080".to_string(),
                protocol: ListenerProtocol::Http,
                tls: None,
                default_route: None,
                request_timeout_secs: 60,
                keepalive_timeout_secs: 75,
                max_concurrent_streams: 100,
                keepalive_max_requests: None,
            }],
            routes: vec![RouteConfig {
                id: "test-route".to_string(),
                priority: Priority::High,
                matches: vec![
                    MatchCondition::Host("example.com".to_string()),
                    MatchCondition::PathPrefix("/api".to_string()),
                    MatchCondition::Header {
                        name: "X-Test".to_string(),
                        value: Some("yes".to_string()),
                    },
                    MatchCondition::Method(vec!["GET".to_string()]),
                ],
                upstream: Some("backend".to_string()),
                service_type: ServiceType::Web,
                policies: RoutePolicies {
                    request_headers: HeaderModifications {
                        rename: HashMap::new(),
                        set: HashMap::from([("X-Forwarded-Proto".to_string(), "https".to_string())]),
                        add: HashMap::from([("X-Extra".to_string(), "value".to_string())]),
                        remove: vec!["X-Internal".to_string()],
                    },
                    response_headers: HeaderModifications {
                        rename: HashMap::new(),
                        set: HashMap::from([("X-Powered-By".to_string(), "Zentinel".to_string())]),
                        add: HashMap::new(),
                        remove: vec![],
                    },
                    ..RoutePolicies::default()
                },
                filters: vec!["redir-0".to_string()],
                builtin_handler: None,
                waf_enabled: false,
                circuit_breaker: None,
                retry_policy: None,
                static_files: None,
                api_schema: None,
                inference: None,
                error_pages: None,
                websocket: false,
                websocket_inspection: false,
                shadow: None,
                fallback: None,
            }],
            upstreams,
            filters,
            agents: vec![],
            waf: None,
            namespaces: vec![],
            limits: Default::default(),
            observability: Default::default(),
            rate_limits: Default::default(),
            cache: None,
            default_upstream: None,
        };

        let writer = ConfigWriter::new(PathBuf::from("/tmp/test.kdl"));
        let kdl = writer.render_kdl(&config);

        // Parse it back using the proxy's KDL parser
        let parsed = zentinel_config::Config::from_kdl(&kdl)
            .unwrap_or_else(|e| panic!("Failed to parse generated KDL:\n{kdl}\n\nError: {e}"));

        // Verify key fields survived the round trip
        assert_eq!(parsed.listeners.len(), 1);
        assert_eq!(parsed.listeners[0].address, "0.0.0.0:8080");
        assert_eq!(parsed.routes.len(), 1);
        assert_eq!(parsed.routes[0].id, "test-route");
        assert_eq!(parsed.routes[0].priority, Priority::High);
        assert_eq!(parsed.routes[0].upstream.as_deref(), Some("backend"));
        assert_eq!(parsed.upstreams.len(), 1);
        assert_eq!(parsed.upstreams["backend"].targets.len(), 2);
        assert_eq!(parsed.upstreams["backend"].targets[0].weight, 3);
        assert_eq!(parsed.filters.len(), 1);
        assert_eq!(parsed.routes[0].filters, vec!["redir-0"]);

        // Verify match conditions
        assert!(parsed.routes[0].matches.iter().any(|m| matches!(m, MatchCondition::Host(h) if h == "example.com")));
        assert!(parsed.routes[0].matches.iter().any(|m| matches!(m, MatchCondition::PathPrefix(p) if p == "/api")));
        assert!(parsed.routes[0].matches.iter().any(|m| matches!(m, MatchCondition::Header { name, value } if name == "X-Test" && value.as_deref() == Some("yes"))));
        assert!(parsed.routes[0].matches.iter().any(|m| matches!(m, MatchCondition::Method(methods) if methods == &["GET"])));

        // Verify header policies
        assert_eq!(
            parsed.routes[0].policies.request_headers.set.get("X-Forwarded-Proto").map(|s| s.as_str()),
            Some("https")
        );
        assert_eq!(parsed.routes[0].policies.request_headers.remove, vec!["X-Internal"]);
        assert_eq!(
            parsed.routes[0].policies.response_headers.set.get("X-Powered-By").map(|s| s.as_str()),
            Some("Zentinel")
        );

        // Verify redirect filter
        match &parsed.filters["redir-0"].filter {
            Filter::Redirect(r) => {
                assert_eq!(r.status_code, 301);
                assert_eq!(r.hostname.as_deref(), Some("example.com"));
                assert_eq!(r.scheme.as_deref(), Some("https"));
            }
            other => panic!("Expected Redirect filter, got {other:?}"),
        }
    }
}
