//! Writes translated Gateway API config as a KDL file for the proxy to read.
//!
//! The gateway controller translates K8s resources into a `Config`, then
//! this module serializes it to a KDL file on a shared volume. The Zentinel
//! proxy runs alongside with `auto-reload: true` and picks up changes
//! automatically via file watching.
//!
//! This is the bridge between the gateway controller (control plane) and
//! the proxy (data plane) in the two-container deployment model.

use std::path::{Path, PathBuf};
use tracing::info;

use zentinel_config::Config;

/// Writes a `Config` to a KDL file that the proxy can read.
pub struct ConfigWriter {
    output_path: PathBuf,
}

impl ConfigWriter {
    pub fn new(output_path: PathBuf) -> Self {
        Self { output_path }
    }

    /// Write the config to disk as KDL.
    ///
    /// Uses an atomic write pattern: write to a temp file, then rename.
    /// This prevents the proxy from reading a partially-written file.
    pub fn write(&self, config: &Config) -> Result<(), std::io::Error> {
        let kdl = self.render_kdl(config);

        let tmp_path = self.output_path.with_extension("kdl.tmp");
        std::fs::write(&tmp_path, &kdl)?;
        std::fs::rename(&tmp_path, &self.output_path)?;

        info!(
            path = %self.output_path.display(),
            routes = config.routes.len(),
            upstreams = config.upstreams.len(),
            listeners = config.listeners.len(),
            bytes = kdl.len(),
            "Config written to disk"
        );

        Ok(())
    }

    /// Get the output path.
    pub fn output_path(&self) -> &Path {
        &self.output_path
    }

    /// Render a Config as KDL text.
    ///
    /// This produces a minimal but complete KDL config that the proxy can
    /// parse. We generate it programmatically rather than using serde because
    /// the KDL format has specific structure expectations.
    fn render_kdl(&self, config: &Config) -> String {
        let mut out = String::with_capacity(4096);

        out.push_str("// Auto-generated by zentinel-gateway controller\n");
        out.push_str("// Do not edit manually, changes will be overwritten\n\n");

        out.push_str(&format!("schema-version \"{}\"\n\n", config.schema_version));

        // System block
        out.push_str("system {\n");
        out.push_str(&format!(
            "    worker-threads {}\n",
            config.server.worker_threads
        ));
        if config.server.auto_reload {
            out.push_str("    auto-reload #true\n");
        }
        out.push_str("}\n\n");

        // Listeners
        out.push_str("listeners {\n");
        for listener in &config.listeners {
            out.push_str(&format!("    listener \"{}\" {{\n", listener.id));
            out.push_str(&format!("        address \"{}\"\n", listener.address));
            let proto = match listener.protocol {
                zentinel_config::ListenerProtocol::Http => "http",
                zentinel_config::ListenerProtocol::Https => "https",
                _ => "http",
            };
            out.push_str(&format!("        protocol \"{proto}\"\n"));

            if let Some(ref tls) = listener.tls {
                out.push_str("        tls {\n");
                if let Some(ref cert) = tls.cert_file {
                    out.push_str(&format!("            cert-file \"{}\"\n", cert.display()));
                }
                if let Some(ref key) = tls.key_file {
                    out.push_str(&format!("            key-file \"{}\"\n", key.display()));
                }
                out.push_str("        }\n");
            }

            out.push_str("    }\n");
        }
        out.push_str("}\n\n");

        // Upstreams
        if !config.upstreams.is_empty() {
            out.push_str("upstreams {\n");
            for (id, upstream) in &config.upstreams {
                out.push_str(&format!("    upstream \"{}\" {{\n", id));
                for target in &upstream.targets {
                    out.push_str(&format!("        target \"{}\"", target.address));
                    if target.weight != 1 {
                        out.push_str(&format!(" weight={}", target.weight));
                    }
                    out.push('\n');
                }

                if let Some(ref hc) = upstream.health_check {
                    out.push_str("        health-check {\n");
                    match &hc.check_type {
                        zentinel_common::types::HealthCheckType::Http {
                            path,
                            expected_status,
                            host,
                        } => {
                            out.push_str("            type \"http\"\n");
                            out.push_str(&format!("            path \"{path}\"\n"));
                            out.push_str(&format!(
                                "            expected-status {expected_status}\n"
                            ));
                            if let Some(ref h) = host {
                                out.push_str(&format!("            host \"{h}\"\n"));
                            }
                        }
                        zentinel_common::types::HealthCheckType::Tcp => {
                            out.push_str("            type \"tcp\"\n");
                        }
                        zentinel_common::types::HealthCheckType::Grpc { service } => {
                            out.push_str("            type \"grpc\"\n");
                            if !service.is_empty() {
                                out.push_str(&format!("            service \"{service}\"\n"));
                            }
                        }
                        _ => {
                            out.push_str("            type \"tcp\"\n");
                        }
                    }
                    out.push_str(&format!("            interval-secs {}\n", hc.interval_secs));
                    out.push_str(&format!("            timeout-secs {}\n", hc.timeout_secs));
                    out.push_str("        }\n");
                }

                out.push_str("    }\n");
            }
            out.push_str("}\n\n");
        }

        // Routes
        if !config.routes.is_empty() {
            out.push_str("routes {\n");
            for route in &config.routes {
                out.push_str(&format!("    route \"{}\" {{\n", route.id));

                // Match conditions
                out.push_str("        match {\n");
                for m in &route.matches {
                    match m {
                        zentinel_config::MatchCondition::PathPrefix(p) => {
                            out.push_str(&format!("            path-prefix \"{p}\"\n"));
                        }
                        zentinel_config::MatchCondition::Path(p) => {
                            out.push_str(&format!("            path \"{p}\"\n"));
                        }
                        zentinel_config::MatchCondition::PathRegex(p) => {
                            out.push_str(&format!("            path-regex \"{p}\"\n"));
                        }
                        zentinel_config::MatchCondition::Host(h) => {
                            out.push_str(&format!("            host \"{h}\"\n"));
                        }
                        zentinel_config::MatchCondition::Header { name, value } => {
                            if let Some(v) = value {
                                out.push_str(&format!("            header \"{name}\" \"{v}\"\n"));
                            } else {
                                out.push_str(&format!("            header \"{name}\"\n"));
                            }
                        }
                        zentinel_config::MatchCondition::Method(methods) => {
                            for method in methods {
                                out.push_str(&format!("            method \"{method}\"\n"));
                            }
                        }
                        zentinel_config::MatchCondition::QueryParam { name, value } => {
                            if let Some(v) = value {
                                out.push_str(&format!(
                                    "            query-param \"{name}\" \"{v}\"\n"
                                ));
                            }
                        }
                    }
                }
                out.push_str("        }\n");

                if let Some(ref upstream) = route.upstream {
                    out.push_str(&format!("        upstream \"{upstream}\"\n"));
                }

                out.push_str("    }\n");
            }
            out.push_str("}\n");
        }

        out
    }
}

/// Write a minimal bootstrap config for the proxy to start with before
/// the controller has reconciled any Gateway API resources.
pub fn write_bootstrap_config(path: &Path) -> Result<(), std::io::Error> {
    let kdl = r#"// Bootstrap config for Zentinel Gateway API controller
// Will be overwritten once the controller reconciles Gateway resources

schema-version "1.0"

system {
    worker-threads 0
    auto-reload #true
}

listeners {
    listener "http" {
        address "0.0.0.0:8080"
        protocol "http"
    }
    listener "https" {
        address "0.0.0.0:8443"
        protocol "http"
    }
}
"#;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, kdl)?;
    info!(path = %path.display(), "Bootstrap config written");
    Ok(())
}
