apiVersion: gateway.networking.k8s.io/v1
date: "2026-03-16T20:47:40+01:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.4.1
implementation:
  contact:
  - '@zentinelproxy'
  organization: zentinelproxy
  project: zentinel
  url: https://github.com/zentinelproxy/zentinel
  version: 0.6.1
kind: ConformanceReport
mode: default
profiles:
- core:
    failedTests:
    - GatewaySecretInvalidReferenceGrant
    - HTTPRouteCrossNamespace
    - HTTPRouteExactPathMatching
    - HTTPRouteHTTPSListener
    - HTTPRouteHeaderMatching
    - HTTPRouteHostnameIntersection
    - HTTPRouteInvalidBackendRefUnknownKind
    - HTTPRouteInvalidCrossNamespaceBackendRef
    - HTTPRouteInvalidCrossNamespaceParentRef
    - HTTPRouteInvalidNonExistentBackendRef
    - HTTPRouteInvalidReferenceGrant
    - HTTPRouteListenerHostnameMatching
    - HTTPRouteMatching
    - HTTPRouteMatchingAcrossRoutes
    - HTTPRoutePartiallyInvalidViaInvalidReferenceGrant
    - HTTPRoutePathMatchOrder
    - HTTPRouteRedirectHostAndStatus
    - HTTPRouteReferenceGrant
    - HTTPRouteRequestHeaderModifier
    - HTTPRouteServiceTypes
    - HTTPRouteSimpleSameNamespace
    - HTTPRouteWeight
    result: failure
    statistics:
      Failed: 22
      Passed: 11
      Skipped: 0
  name: GATEWAY-HTTP
  summary: Core tests failed with 22 test failures.
