name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before proposing a feature, please read the [Manifesto](https://github.com/zentinelproxy/zentinel/blob/main/MANIFESTO.md).

        Zentinel values **predictability over flexibility** and **calm operation over feature breadth**.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: It would be great if Zentinel could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        - Using an external agent to...
        - Workaround with...
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Where does this belong?
      description: Based on the Manifesto, where should this live?
      options:
        - Core proxy (requires strong justification)
        - External agent
        - Configuration option
        - Documentation improvement
        - Not sure
    validations:
      required: true

  - type: checkboxes
    id: manifesto
    attributes:
      label: Manifesto Alignment
      description: Does this feature align with Zentinel's principles?
      options:
        - label: This feature can be **bounded** (has clear limits)
        - label: This feature can be **observed** (metrics, logs)
        - label: This feature can **fail safely** (explicit failure modes)
        - label: This feature does not add **implicit behavior**

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the [Manifesto](https://github.com/zentinelproxy/zentinel/blob/main/MANIFESTO.md)
          required: true
