apiVersion: gateway.networking.k8s.io/v1
date: "2026-03-19T07:20:48+01:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.4.1
implementation:
  contact:
  - '@zentinelproxy'
  organization: zentinelproxy
  project: zentinel
  url: https://github.com/zentinelproxy/zentinel
  version: 0.6.1
kind: ConformanceReport
mode: default
profiles:
- core:
    failedTests:
    - GatewaySecretInvalidReferenceGrant
    - HTTPRouteHTTPSListener
    - HTTPRouteInvalidCrossNamespaceParentRef
    - HTTPRouteInvalidReferenceGrant
    - HTTPRouteServiceTypes
    - HTTPRouteWeight
    result: failure
    statistics:
      Failed: 6
      Passed: 27
      Skipped: 0
  name: GATEWAY-HTTP
  summary: Core tests failed with 6 test failures.
